# override compose file for production

version: "3.9"
services:

  # backend fastapi container
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: rmckay1763/backend-prod
    container_name: backend-prod

  # frontend node js container
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: rmckay1763/frontend-prod
    container_name: frontend-prod
    ports:
      - "80:80"
      - "8000:8000"