# base docker compose file

version: "3.9"
services:
  
  # userinfo database container
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=userinfo
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # database migration container
  migration:
    build: ./postgres
    image: migration
    container_name: migration
    depends_on:
      - "postgres"
  
  # backend fastapi container
  backend:
    image: backend
    container_name: backend
  
  # frontend node js container
  frontend:
    image: frontend
    container_name: frontend

# internal volumes
volumes:
  postgres-data:
