# override compose file for production

version: "3.9"
services:

  # backend fastapi container
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: registry.gitlab.com/g5003/predicting-patient-issues-mirror/backend-prod
    container_name: backend-prod

   # ml server container
  ml-server:
    build:
      context: ./ml-server
      dockerfile: Dockerfile.prod
    image: registry.gitlab.com/g5003/predicting-patient-issues-mirror/ml-server-prod
    container_name: ml-server-prod

  # ml scheduler container
  ml-scheduler:
    build: ./ml-scheduler
    image: registry.gitlab.com/g5003/predicting-patient-issues-mirror/ml-scheduler-prod
    container_name: ml-scheduler-prod

  # frontend node js container
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: registry.gitlab.com/g5003/predicting-patient-issues-mirror/frontend-prod
    container_name: frontend-prod
    ports:
      - "80:80"