version: "3.9"
services:
  
  # userinfo database container
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=userinfo
    expose:
      - "5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  # backend fastapi container
  backend:
    build: ./backend
    image: backend
    ports:
      - "8000:8000"
    depends_on:
      - "postgres"
    volumes:
      - "./backend:/app/backend"
  
  # frontend node js container
  frontend:
    build: ./frontend
    image: frontend
    ports:
      - "80:5000"
    volumes:
      - "./frontend:/app/frontend"
  
