version: "3.9"
services:
  
  # userinfo database
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=userinfo
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  # backend api service
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - "postgres"
    volumes:
      - "./backend:/app/backend"
  
  # frontend web app
  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    volumes:
      - "./frontend:/app/frontend"
  
