# base docker compose file

version: "3.9"
services:
  
  # userinfo database container
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # database migration container
  migration:
    build: ./postgres
    image: registry.gitlab.com/g5003/predicting-patient-issues-mirror/migration
    container_name: migration
    depends_on:
      - "postgres"

  # machine learning container
  # ml:
  #   build: ./ml
  #   image: registry.gitlab.com/g5003/predicting-patient-issues-mirror/ml
  #   container_name: ml-dev
  #   volumes:
  #     - "./ml:/app"

# internal volumes
volumes:
  postgres-data:
