version: "3.9"
services:
  # backend api service
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/app/backend"
  # frontend web app
  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    volumes:
      - "./frontend:/app/frontend"