# base docker compose file

version: "3.9"
services:
  
  # userinfo database container
  postgres:
    image: postgres:14
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=userinfo
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # database migration container
  migration:
    image: registry.gitlab.com/g5003/predicting-patient-issues-mirror/migration:iteration-2
    container_name: dbmate
    depends_on:
      - "postgres"

  # backend fastapi container
  backend:
    image: registry.gitlab.com/g5003/predicting-patient-issues-mirror/backend-prod:iteration-2
    container_name: app-backend
    restart: always

  # frontend node js container
  frontend:
    image: registry.gitlab.com/g5003/predicting-patient-issues-mirror/frontend-prod:iteration-2
    container_name: app-frontend
    restart: always
    ports:
      - "80:80"

# internal volumes
volumes:
  postgres-data: