# override compose file for development

version: "3.9"
services:
  
  # backend fastapi container
  backend:
    build: ./backend
    image: registry.gitlab.com/g5003/predicting-patient-issues-mirror/backend-dev
    container_name: backend-dev
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/app"

  # ml server container
  ml-server:
    build: ./ml-server
    image: registry.gitlab.com/g5003/predicting-patient-issues-mirror/ml-server-dev
    container_name: ml-server-dev
    ports:
      - "8001:8000"
    volumes:
      - "./ml-server:/app"

  # ml scheduler container
  ml-scheduler:
    build: ./ml-scheduler
    image: registry.gitlab.com/g5003/predicting-patient-issues-mirror/ml-scheduler-dev
    container_name: ml-scheduler-dev
    volumes:
      - "./ml-scheduler/code:/code"
  
  # frontend node js container
  frontend:
    build: ./frontend
    image: registry.gitlab.com/g5003/predicting-patient-issues-mirror/frontend-dev
    container_name: frontend-dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5000:5000"
    volumes:
      - "./frontend/src:/app/frontend/src"
