# docker build file for backend production

# image with fastapi and gunicorn
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

WORKDIR /app

# add source code
COPY . .

# install dependencies
RUN \
    pip3 install --upgrade pip && \
    pip3 install pipreqs && \
    pipreqs --force . && \
    pip3 install --no-cache-dir --upgrade -r requirements.txt