# docker build file for backend tests

# base python image
FROM python:3.9

# set backend directory
WORKDIR /app

# add source code
COPY . .

# install dependencies
RUN \
    pip3 install --upgrade pip && \
    pip3 install pytest && \
    pip3 install pipreqs && \
    pipreqs --force . && \
    pip3 install --no-cache-dir --upgrade -r requirements.txt

# expose port for api
EXPOSE 8000

# start api service
#CMD ["python3", "tests.py"]
CMD ["python3", "-m", "pytest"]