# docker build file for backend production

# image with fastapi and gunicorn
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

# add dependencies file
COPY requirements.prod.txt /app/requirements.txt

# install dependencies
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

# add source code
COPY . /app